set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)
set(VCPKG_BUILD_TYPE release)

if(PORT MATCHES "(boost-cobalt)")
    set(VCPKG_C_FLAGS "-DBOOST_COBALT_NO_PMR")
    set(VCPKG_CXX_FLAGS "-BOOST_COBALT_NO_PMR")
endif()
